manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: genteure
      url-base: https://github.com/Genteure
  projects:
    - name: zmk
      remote: genteure
      revision: ce880fa6e41dd587c1a1feb2d85d07af18a1e017
      import: app/west.yml
  self:
    path: config
